# For details see https://documenteer.lsst.io/guides/toml-reference.html

[project]
title = "In-Kind Program"
copyright = "2025"
base_url = "https://in-kind-program.lsst.io"
github_url = "https://github.com/lsst/in-kind-program"
version = "Current"

[sphinx]
rst_epilog_file = "rst_epilog.rst"
